Debian: removing dependency to deamon package

diff --git a/deploy/deb/etc/init.d/git-as-svn b/deploy/deb/etc/init.d/git-as-svn
--- a/deploy/deb/etc/init.d/git-as-svn
+++ b/deploy/deb/etc/init.d/git-as-svn
@@ -1,7 +1,4 @@
-#!/bin/bash
-# /etc/init.d/git-as-svn
-# debian-compatible git-as-svn startup script.
-#
+#! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          git-as-svn
 # Required-Start:    $remote_fs $syslog $network
@@ -12,223 +9,155 @@
 # Description:       Controls git-as-svn server
 ### END INIT INFO
 
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
+# Author: Artem V. Navrotskiy <bozaro@bozaro.ru>
 
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Subversion frontend for git repositories"
 NAME=git-as-svn
+PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
-PIDFILE=/var/run/$NAME/$NAME.pid
-GAS_LOG=/var/log/$NAME/$NAME.log
+JAVA=/usr/bin/java
+GAS_JAR=/usr/share/git-as-svn/lib/git-as-svn.jar
+GAS_CONFIG=/etc/git-as-svn/git-as-svn.conf
 GAS_USER=git
 GAS_GROUP=git
-JAVA=/usr/bin/java
 
+# Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-DAEMON=/usr/bin/daemon
-DAEMON_ARGS="--name=$NAME --inherit --output=$GAS_LOG --pidfile=$PIDFILE"
+# Exit if the package is not installed
+[ -r "$GAS_JAR" ] || exit 0
+[ -r "$GAS_CONFIG" ] || exit 0
 
-if [ -n "$UMASK" ]; then
-    DAEMON_ARGS="$DAEMON_ARGS --umask=$UMASK"
-fi
-
-SU=/bin/su
-
-# load environments
-if [ -r /etc/default/locale ]; then
-  . /etc/default/locale
-  export LANG LANGUAGE
-elif [ -r /etc/environment ]; then
-  . /etc/environment
-  export LANG LANGUAGE
-fi
-
+DAEMON=$JAVA
+DAEMON_NAME=java
+DAEMON_ARGS="$JAVA_OPTS -jar $GAS_JAR --config $GAS_CONFIG $GAS_ARGS"
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
 
 # Define LSB log_* functions.
-# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
 . /lib/lsb/init-functions
-
-# Exit if the package is not installed
-if [ ! -x "$DAEMON" ]; then
-    echo "daemon package not installed" >&2
-    exit 1
-fi
-
-# Make sure we run as root, since setting the max open files through
-# ulimit requires root access
-if [ `id -u` -ne 0 ]; then
-    echo "The $NAME init script can only be run as root"
-    exit 1
-fi
 
 #
 # Function that starts the daemon/service
 #
 do_start()
 {
-    # the default location is /var/run/git-as-svn/git-as-svn.pid but the parent directory needs to be created
-    mkdir -p `dirname $PIDFILE`
-    chown $GAS_USER `dirname $PIDFILE`
-    # Return
-    #   0 if daemon has been started
-    #   1 if daemon was already running
-    #   2 if daemon could not be started
-    $DAEMON $DAEMON_ARGS --running && return 1
-
-    # If the var MAXOPENFILES is enabled in /etc/default/git-as-svn then set the max open files to the 
-    # proper value
-    if [ -n "$MAXOPENFILES" ]; then
-        [ "$VERBOSE" != no ] && echo Setting up max open files limit to $MAXOPENFILES
-        ulimit -n $MAXOPENFILES
-    fi
-
-    # notify of explicit umask
-    if [ -n "$UMASK" ]; then
-        [ "$VERBOSE" != no ] && echo Setting umask to $UMASK
-    fi
-
-    # --user in daemon doesn't prepare environment variables like HOME, USER, LOGNAME or USERNAME,
-    # so we let su do so for us now
-    $SU -l $GAS_USER --shell=/bin/bash -c "$DAEMON $DAEMON_ARGS -- $JAVA $JAVA_OPTS -jar /usr/share/git-as-svn/lib/git-as-svn.jar --config /etc/git-as-svn/git-as-svn.conf $GAS_ARGS" || return 2
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --user $GAS_USER --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --user $GAS_USER --background --chuid $GAS_USER:$GAS_GROUP --make-pidfile -- \
+		$DAEMON_ARGS \
+		|| return 2
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
 }
-
-
-#
-# Verify that all git-as-svn processes have been shutdown
-# and if not, then do killall for them
-# 
-get_running() 
-{
-    return `ps -U $GAS_USER --no-headers -f | egrep -e '(java|daemon)' | grep -c . `
-}
-
-force_stop() 
-{
-    get_running
-    if [ $? -ne 0 ]; then 
-	killall -u $GAS_USER java daemon || return 3
-    fi
-}
-
-# Get the status of the daemon process
-get_daemon_status()
-{
-    if [ ! -r "$PIDFILE" ]; then
-        return 1
-    fi
-    $DAEMON $DAEMON_ARGS --running || return 1
-}
-
 
 #
 # Function that stops the daemon/service
 #
 do_stop()
 {
-    # Return
-    #   0 if daemon has been stopped
-    #   1 if daemon was already stopped
-    #   2 if daemon could not be stopped
-    #   other if a failure occurred
-    get_daemon_status
-    case "$?" in
-	0) 
-	    $DAEMON $DAEMON_ARGS --stop || return 2
-        # wait for the process to really terminate
-        for n in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
-            sleep 1
-            $DAEMON $DAEMON_ARGS --running || break
-        done
-        if get_daemon_status; then
-	        force_stop || return 3
-        fi
-	    ;;
-	*)
-	    force_stop || return 3
-	    ;;
-    esac
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $DAEMON_NAME --user $GAS_USER
 
-    # Many daemons don't delete their pidfiles when they exit.
-    rm -f $PIDFILE
-    return 0
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	#start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	#[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $DAEMON_NAME --user $GAS_USER
+	return 0
 }
 
 case "$1" in
   start)
-    log_daemon_msg "Starting $DESC" "$NAME"
-    do_start
-    case "$?" in
-        0|1) log_end_msg 0 ;;
-        2) log_end_msg 1 ;;
-    esac
-    ;;
-  stop)
-    log_daemon_msg "Stopping $DESC" "$NAME"
-    do_stop
-    case "$?" in
-        0|1) log_end_msg 0 ;;
-        2) log_end_msg 1 ;;
-    esac
-    ;;
-  restart|force-reload)
-    #
-    # If the "reload" option is implemented then remove the
-    # 'force-reload' alias
-    #
-    log_daemon_msg "Restarting $DESC" "$NAME"
-    do_stop
-    case "$?" in
-      0|1)
-        do_start
-        case "$?" in
-          0) log_end_msg 0 ;;
-          1) log_end_msg 1 ;; # Old process is still running
-          *) log_end_msg 1 ;; # Failed to start
-        esac
-        ;;
-      *)
-  	# Failed to stop
-	log_end_msg 1
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
-    esac
-    ;;
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
   status)
-	get_daemon_status
-	case "$?" in 
-	 0) 
-		echo "$DESC is running with the pid `cat $PIDFILE`"
-		rc=0
+	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
 		;;
-	*) 
-		get_running
-		procs=$?
-		if [ $procs -eq 0 ]; then 
-			echo -n "$DESC is not running"
-			if [ -f $PIDFILE ]; then 
-				echo ", but the pidfile ($PIDFILE) still exists"
-				rc=1
-			else 
-				echo
-				rc=3
-			fi
-		
-		else 
-			echo "$procs instances of git-as-svn are running at the moment"
-			echo "but the pidfile $PIDFILE is missing"
-			rc=0
-		fi
-		
-		exit $rc
+	  *)
+		# Failed to stop
+		log_end_msg 1
 		;;
 	esac
 	;;
   *)
-    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
-    exit 3
-    ;;
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
 esac
 
-exit 0
+:
